name: PR preview

on:
  pull_request_target:
    types: [opened, synchronize]

permissions:
  content: read

jobs:
  preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          persist-credentials: false
      - name: Preview
        run: echo "Preview ready for PR ${{ github.event.pull_request.number }}"
